
# version: '3'
# services:
#   your-app:
#     image: customer
#     ports:
#       - "9092:9092"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/china_ayur
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: root


version: "3"
services:
  application:
    image: china324/customers
    ports:
      - "9092:9092"
    networks:
      - springboot-customer
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:8.0.19
    networks:
      - springboot-customer
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer
    volumes:
      - /data/mysql
networks:
  springboot-customer:
